# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alexander.kohn/xaui_0_ex/project_1_testxaui/project_1_testxaui.srcs/sources_1/ip/ila_1/ila_1.xci
# IP: The module: 'ila_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexander.kohn/xaui_0_ex/project_1_testxaui/project_1_testxaui.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/alexander.kohn/xaui_0_ex/project_1_testxaui/project_1_testxaui.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/alexander.kohn/xaui_0_ex/project_1_testxaui/project_1_testxaui.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/alexander.kohn/xaui_0_ex/project_1_testxaui/project_1_testxaui.srcs/sources_1/ip/ila_1/ila_1.xci
# IP: The module: 'ila_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexander.kohn/xaui_0_ex/project_1_testxaui/project_1_testxaui.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/alexander.kohn/xaui_0_ex/project_1_testxaui/project_1_testxaui.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/alexander.kohn/xaui_0_ex/project_1_testxaui/project_1_testxaui.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
